/**
 * Firestore challenge IDs for the benchmark tasks.
 *
 * v2 / Run-2 IDs (generated by seed-to-platform.ts on 2026-04-04):
 *   maxcut-g200:        ch_bench_onxf48mfic1gxv2e
 *   circle-packing-n20: ch_bench_ud9ae8gh27e5dmgf
 *   difference-bases:   ch_bench_jqyo8gwozh9pkzyn
 *   flat-poly-deg50:    ch_bench_c1fpbzjqjs43xpji
 *   tsp-100:            ch_bench_6yll5au03pmzu3xb
 *   hp-folding-48mer:   ch_bench_vff8q5o7gipoqm0o  (DROPPED from benchmark; kept for archive)
 *   lj-n41:             ch_bench_ud4cxzu0c7rvuqqf
 *   erdos-overlap:      ch_bench_njhlgq06ouu7ohlw
 *
 * Run-1 IDs (kept here for archive reference; not used by run-full.ts):
 *   maxcut-g200:        ch_bench_71qs8npijpnvky4q
 *   circle-packing-n20: ch_bench_d1v5b25w8y3jk58a
 *   difference-bases:   ch_bench_4syi46tpyxhd5jp2
 *   flat-poly-deg50:    ch_bench_0qjyvb1amfhddk1v
 *   tsp-100:            ch_bench_l9x80j6i5n2q27ic
 *   hp-folding-48mer:   ch_bench_u6r7yzs8apfkkz89
 *   lj-n41:             ch_bench_42dj6zp8mz7hjrjt
 *   erdos-overlap:      ch_bench_btmj7mk7aetnn65a
 *
 * Cards 9–12 (new tasks added 2026-04-08, seeded 2026-04-08):
 *   bench-maxcut-g200-s99:    ch_bench_r51isvqeglm6feqb
 *   bench-graph-coloring-g80: ch_bench_l637t546sufugy6e
 *   bench-tsp-50:             ch_bench_amy5xqfggjky2pmi
 *   bench-molecule-qed:       ch_bench_cxbn0yvml5v91zow
 *
 * Cards 13–16 (new tasks added 2026-04-09, seeded 2026-04-09):
 *   bench-tfbind-10:          ch_bench_kfhfy5zpd5lgqol7
 *   bench-heilbronn-n12:      ch_bench_20p5qefrvs2cm2qj
 *   bench-kissing-11d:        ch_bench_jv67nq0ffxyvujoc
 *   bench-3ap-free-100:       ch_bench_8dwuookpbxchhysz
 *
 * Cards 17–18 (new tasks 2026-04-21, seeded 2026-04-21):
 *   bench-knapsack-50:        ch_bench_m2f7davw55psymvk
 *   bench-set-cover-60:       ch_bench_kduo9ly2god9bjvx
 *
 * Prospective tasks (2026-04-23) — composability validation extension:
 *   bench-max-k-coverage-n100: ch_mobpqvl5vlg7e4mc  (HIGH composability, prediction v2)
 *   bench-latin-square-9:      ch_mobpqydsniv76xa2  (LOW composability, prediction v2)
 */
export const BENCHMARK_CHALLENGE_IDS: Record<string, string> = {
  // ── v2 core tasks ────────────────────────────────────────────────────────────
  'bench-maxcut-g200':        'ch_bench_onxf48mfic1gxv2e',
  'bench-circle-packing-n20': 'ch_bench_ud9ae8gh27e5dmgf',
  'bench-difference-bases':   'ch_bench_jqyo8gwozh9pkzyn',
  'bench-flat-poly-deg50':    'ch_bench_c1fpbzjqjs43xpji',
  'bench-tsp-100':            'ch_bench_6yll5au03pmzu3xb',
  'bench-hp-folding-48mer':   'ch_bench_vff8q5o7gipoqm0o',  // dropped; keep for archive
  'bench-lj-n41':             'ch_bench_ud4cxzu0c7rvuqqf',
  'bench-erdos-overlap':      'ch_bench_njhlgq06ouu7ohlw',
  // ── Cards 9–12: new tasks (2026-04-08) — SEEDED 2026-04-08 ──────────────────
  'bench-maxcut-g200-s99':    'ch_bench_r51isvqeglm6feqb',
  'bench-graph-coloring-g80': 'ch_bench_l637t546sufugy6e',
  'bench-tsp-50':             'ch_bench_amy5xqfggjky2pmi',
  'bench-molecule-qed':       'ch_bench_cxbn0yvml5v91zow',
  // ── Cards 13–16: new tasks (2026-04-09) — SEEDED 2026-04-09 ─────────────────
  'bench-tfbind-10':          'ch_bench_kfhfy5zpd5lgqol7',
  'bench-heilbronn-n12':      'ch_bench_20p5qefrvs2cm2qj',
  'bench-kissing-11d':        'ch_bench_jv67nq0ffxyvujoc',
  'bench-3ap-free-100':       'ch_bench_8dwuookpbxchhysz',
  // ── Cards 17–18: new composable tasks (2026-04-21) — SEEDED 2026-04-21 ──────
  'bench-knapsack-50':        'ch_bench_m2f7davw55psymvk',
  'bench-set-cover-60':       'ch_bench_kduo9ly2god9bjvx',
  // ── Prospective tasks (2026-04-23): composability validation extension ────────
  'bench-max-k-coverage-n100': 'ch_mobpqvl5vlg7e4mc',
  'bench-latin-square-9':      'ch_mobpqydsniv76xa2',
};
